Issue 2050
CSPS-EFPC-IT/matomo-single-node-azure pull request #19
Opened 2023-01-19 19:37 UTC by cedricguindon

2023-01-19 20:20 UTC, PatrickMessierGoC requested changes

2023-01-19 20:20 UTC, PatrickMessierGoC commented on armTemplates/azuredeploy.json
> +			"type": "string",
securestring

2023-01-19 20:20 UTC, PatrickMessierGoC commented on armTemplates/azuredeploy.json
> +			"type": "string",
securestring

2023-01-19 20:20 UTC, PatrickMessierGoC commented on armTemplates/azuredeploy.json
> +								{
À supprimer

2023-01-19 20:20 UTC, PatrickMessierGoC commented on armTemplates/azuredeploy.json
> +				"maxNumberOfRecordSets": 25000,
à supprimer. 
Ref.: https://learn.microsoft.com/en-us/azure/templates/microsoft.network/2018-09-01/privatednszones?pivots=deployment-language-arm-template#privatezoneproperties-1

2023-01-20 12:03 UTC, cedricguindon commented on armTemplates/azuredeploy.json
> +			"type": "string",
done

2023-01-20 12:04 UTC, cedricguindon commented on armTemplates/azuredeploy.json
> +			"type": "string",
done

2023-01-20 12:04 UTC, cedricguindon commented on armTemplates/azuredeploy.json
> +			"type": "string",
done

2023-01-20 12:05 UTC, cedricguindon commented on README.md
> +- Mysql client 8.0
done

2023-01-20 12:09 UTC, cedricguindon commented on taskGroups/DeployMatomoSingleNode.json
> +        "overrideParameters": "-applicationCustomFqdn \"$(applicationCustomFqdn)\" -armTemplateRepoBaseUrl \"$(armTemplateRepoBaseUrl)\" -configurationAuditLogEnabled \"$(configurationAuditLogEnabled
done

2023-01-20 12:11 UTC, cedricguindon commented on armTemplates/azuredeploy.json
> +				"maxNumberOfRecordSets": 25000,
done

2023-01-20 13:35 UTC, PatrickMessierGoC approved these changes

2023-01-20 13:39 UTC, merged